version: "3.7"
services:
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        app_env: ${APP_ENV}
    volumes:
      - './src:/app/src'
    restart: on-failure
    ports:
      - "3000:3000"
